// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.ManageStatuses;

[GenerateTypedNameReferences]
public sealed partial class ManageStatusesWindow : DefaultWindow
{
    public event Action<string>? OnAddStatus;
    public event Action<string>? OnRemoveStatus;

    private List<KeyValuePair<string, string>> _allStatuses = new();
    private HashSet<string> _activeStatuses = new();

    public ManageStatusesWindow()
    {
        RobustXamlLoader.Load(this);

        AvailableStatusesList.OnItemSelected += _ => AddStatusButton.Disabled = false;
        AvailableStatusesList.OnItemDeselected += _ => AddStatusButton.Disabled = true;
        ActiveStatusesList.OnItemSelected += _ => RemoveStatusButton.Disabled = false;
        ActiveStatusesList.OnItemDeselected += _ => RemoveStatusButton.Disabled = true;

        AddStatusButton.OnPressed += _ =>
        {
            if (AvailableStatusesList.GetSelected().FirstOrDefault() is { } item)
                OnAddStatus?.Invoke((string)item.Metadata!);
        };

        RemoveStatusButton.OnPressed += _ =>
        {
            if (ActiveStatusesList.GetSelected().FirstOrDefault() is { } item)
                OnRemoveStatus?.Invoke((string)item.Metadata!);
        };

        SearchAvailable.OnTextChanged += _ => RefreshLists();
        SearchActive.OnTextChanged += _ => RefreshLists();
    }

    public void UpdateState(string targetName, List<string> activeStatuses, Dictionary<string, string> allStatuses)
    {
        TargetLabel.Text = Loc.GetString("admin-verbs-traits-target-player", ("player", targetName));
        _activeStatuses = activeStatuses.ToHashSet();
        _allStatuses = allStatuses.OrderBy(x => x.Value).ToList();
        RefreshLists();
    }

    private void RefreshLists()
    {
        AvailableStatusesList.Clear();
        ActiveStatusesList.Clear();
        AddStatusButton.Disabled = true;
        RemoveStatusButton.Disabled = true;

        var searchAvailable = SearchAvailable.Text ?? "";
        var searchActive = SearchActive.Text ?? "";

        foreach (var (id, name) in _allStatuses.OrderBy(x => x.Value))
        {
            if (_activeStatuses.Contains(id))
            {
                if (string.IsNullOrEmpty(searchActive) ||
                    name.Contains(searchActive, StringComparison.OrdinalIgnoreCase) ||
                    id.Contains(searchActive, StringComparison.OrdinalIgnoreCase))
                {
                    ActiveStatusesList.AddItem(name).Metadata = id;
                }
            }
            else
            {
                if (string.IsNullOrEmpty(searchAvailable) ||
                    name.Contains(searchAvailable, StringComparison.OrdinalIgnoreCase) ||
                    id.Contains(searchAvailable, StringComparison.OrdinalIgnoreCase))
                {
                    AvailableStatusesList.AddItem(name).Metadata = id;
                }
            }
        }
    }
}
