// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.ManageTraits;

[GenerateTypedNameReferences]
public sealed partial class ManageTraitsWindow : DefaultWindow
{
    public event Action<string, bool>? OnAddTrait;
    public event Action<string>? OnRemoveTrait;
    private List<KeyValuePair<string, string>> _allTraits = new();
    private HashSet<string> _activeTraits = new();

    public ManageTraitsWindow()
    {
        RobustXamlLoader.Load(this);

        AvailableTraitsList.OnItemSelected += _ => AddTraitButton.Disabled = false;
        AvailableTraitsList.OnItemDeselected += _ => AddTraitButton.Disabled = true;
        ActiveTraitsList.OnItemSelected += _ => RemoveTraitButton.Disabled = false;
        ActiveTraitsList.OnItemDeselected += _ => RemoveTraitButton.Disabled = true;

        AddTraitButton.OnPressed += _ =>
        {
            if (AvailableTraitsList.GetSelected().FirstOrDefault() is { } item)
                OnAddTrait?.Invoke((string)item.Metadata!, SpawnGearCheckBox.Pressed);
        };

        RemoveTraitButton.OnPressed += _ =>
        {
            if (ActiveTraitsList.GetSelected().FirstOrDefault() is { } item)
                OnRemoveTrait?.Invoke((string)item.Metadata!);
        };

        SearchAvailable.OnTextChanged += _ => RefreshLists();
        SearchActive.OnTextChanged += _ => RefreshLists();
    }

    public void UpdateState(string targetName, List<string> activeTraits, Dictionary<string, string> allTraits)
    {
        TargetLabel.Text = Loc.GetString("admin-verbs-traits-target-player", ("player", targetName));
        _activeTraits = activeTraits.ToHashSet();
        _allTraits = allTraits.OrderBy(x => x.Value).ToList();
        RefreshLists();
    }

    private void RefreshLists()
    {
        AvailableTraitsList.Clear();
        ActiveTraitsList.Clear();
        AddTraitButton.Disabled = true;
        RemoveTraitButton.Disabled = true;

        var searchAvailable = SearchAvailable.Text?.ToLowerInvariant() ?? "";
        var searchActive = SearchActive.Text?.ToLowerInvariant() ?? "";

        foreach (var (id, name) in _allTraits)
        {
            if (_activeTraits.Contains(id))
            {
                if (string.IsNullOrEmpty(searchActive) || name.ToLowerInvariant().Contains(searchActive) ||
                    id.ToLowerInvariant().Contains(searchActive))
                    ActiveTraitsList.AddItem(name).Metadata = id;
            }
            else
            {
                if (string.IsNullOrEmpty(searchAvailable) || name.ToLowerInvariant().Contains(searchAvailable) ||
                    id.ToLowerInvariant().Contains(searchAvailable))
                    AvailableTraitsList.AddItem(name).Metadata = id;
            }
        }
    }
}
