- type: entity
  id: BaseProjectileFragment
  name: fragment
  parent: BaseItem
  abstract: true
  components:
  - type: Sprite
    sprite: SS220/Objects/Weapons/fragments.rsi
    state: metal-1
  - type: Item
    size: Tiny
  - type: Tag
    tags:
    - Trash
