
// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using System.Text;
using Content.Client.Message;
using Content.Shared.SS220.Surgery.Graph;
using Content.Shared.SS220.Utility;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.SS220.Surgery.NodeGraphUi;

[GenerateTypedNameReferences]
public sealed partial class EdgeDescription : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    private readonly SurgeryGraphSystem _surgeryGraph = default!;

    private static readonly LocId EdgeName = "operation-description-edge-to";
    private static readonly LocId EdgeNameSameNode = "operation-description-edge-to-same-node";

    private static readonly LocId OperationDescriptionConditionSection = "operation-description-condition-section-name";
    private static readonly LocId OperationDescriptionActionDescriptions = "operation-description-action-description-section-name";

    public EdgeDescription()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _surgeryGraph = _entityManager.System<SurgeryGraphSystem>();
    }

    public void SetEdgeInfo(SurgeryGraphEdge edge, string nodeId)
    {
        var edgeName = edge.Target != nodeId
            ? Loc.GetString(EdgeName, ("to", Loc.GetString(edge.Target)), ("edgeName", Loc.GetString(edge.EdgeTooltip)))
            : Loc.GetString(EdgeNameSameNode, ("edgeName", Loc.GetString(edge.EdgeTooltip)));

        EdgeNameLabel.SetMarkup(edgeName);

        AddDescriptionInfo(edge);
        AddConditionInfo(edge);
    }

    private void AddDescriptionInfo(SurgeryGraphEdge edge)
    {
        var actionLocIds = _surgeryGraph.GetActionsLocIds(edge);
        if (actionLocIds.Count == 0)
            return;

        var builder = new StringBuilder();
        builder.AppendJoin('\n', actionLocIds.Select(x => Loc.GetString(x)));
        EdgeActionDescriptionsLabel.SetMarkup(builder.ToString());
    }

    private void AddConditionInfo(SurgeryGraphEdge edge)
    {
        var surgeryRequirements = _surgeryGraph.GetRequirements(edge);
        if (surgeryRequirements.Count == 0)
            return;

        var builder = new StringBuilder();
        builder.Append(Loc.GetString(OperationDescriptionConditionSection));
        foreach (var requirement in surgeryRequirements)
        {
            builder.AppendLine();
            builder.Append(requirement.RequirementDescription(_prototypeManager, _entityManager));
        }

        this.TooltipSupplier = CreateRichTooltip;
        this.ToolTip = builder.ToString();
    }

    private Tooltip CreateRichTooltip(Control hovered)
    {
        var tooltip = new Tooltip()
        {
            Tracking = hovered.TrackingTooltip,
        };

        if (FormattedMessage.TryFromMarkup(hovered.ToolTip ?? "", out var message))
        {
            tooltip.SetMessage(message);
        }
        else
        {
            tooltip.Text = hovered.ToolTip;
        }

        return tooltip;
    }

}
