// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using Content.Shared.SS220.Surgery.Graph;
using Robust.Client.Player;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client.Message;
using Robust.Shared.Input;

namespace Content.Client.SS220.Surgery.NodeGraphUi;

[GenerateTypedNameReferences]
public sealed partial class OperationNodeLabel : BoxContainer
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly SurgeryGraphSystem _surgeryGraph = default!;

    public string NodeId { private set; get; } = string.Empty;

    private static readonly Color OperationDescriptionBullet = Color.FromHex("#e42003");
    private static readonly LocId NodeName = "operation-description-node-name-text";

    public bool EdgesVisible
    {
        get;
        set
        {
            EdgesDescriptionContainer.Visible = value;
            field = value;
        }
    }

    public OperationNodeLabel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _surgeryGraph = _entityManager.System<SurgeryGraphSystem>();

        NodeHeaderContainer.OnKeyBindDown += (args) =>
        {
            if (args.Function == EngineKeyFunctions.Use || args.Function != EngineKeyFunctions.UIClick)
                return;

            EdgesVisible = !EdgesVisible;
            UpdateVisible();
        };
    }

    public void SetNodeInfo(SurgeryGraphNode node)
    {
        NodeId = node.Name;
        NodeRichTextLabel.SetMarkup(Loc.GetString(NodeName, ("nodeName", Loc.GetString(NodeId))));

        if (node.Edges.Count == 0)
        {
            UpdateVisible();
            return;
        }

        if (_player.LocalEntity is not { Valid: true } playerEntity)
            return;

        foreach (var edge in node.Edges)
        {
            var edgeVisible = _surgeryGraph.GetVisibilityRequirements(edge).All(x => x.MeetRequirement(playerEntity, playerEntity, _entityManager));
            if (!edgeVisible)
                continue;

            var edgeDescription = new EdgeDescription();
            edgeDescription.SetEdgeInfo(edge, node.Name);
            EdgesDescriptionContainer.AddChild(edgeDescription);

            EdgesDescriptionContainer.Visible = false;
        }

        UpdateVisible();
    }

    public void SetActive(bool active)
    {
        CurrentNodeFoldedIcon.ModulateSelfOverride = active ? OperationDescriptionBullet : null;
        CurrentNodeOpenIcon.ModulateSelfOverride = active ? OperationDescriptionBullet : null;
        CurrentNodeNoEdgeIcon.ModulateSelfOverride = active ? OperationDescriptionBullet : null;
    }

    private void UpdateVisible()
    {
        if (EdgesDescriptionContainer.ChildCount == 0)
        {
            CurrentNodeFoldedIcon.Visible = false;
            CurrentNodeOpenIcon.Visible = false;
            CurrentNodeNoEdgeIcon.Visible = true;
            return;
        }

        CurrentNodeNoEdgeIcon.Visible = false;

        CurrentNodeFoldedIcon.Visible = !EdgesVisible;
        CurrentNodeOpenIcon.Visible = EdgesVisible;
    }
}
