// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.Surgery;
using Content.Shared.SS220.Surgery.Graph;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.SS220.Surgery.SurgeryStartUi;

[GenerateTypedNameReferences]
public sealed partial class SurgeryDrapeMenu : FancyWindow
{
    public event Action<ProtoId<SurgeryGraphPrototype>, EntityUid>? OnSurgeryConfirmClicked;

    public EntityUid Target;
    public EntityUid Used;

    private Dictionary<SurgeryPuppetPart, HashSet<Control>> _operations = new();

    private static readonly LocId HeaderText = "surgery-start-ui-target";
    private static readonly LocId FooterConfirm = "surgery-footer-confirm";

    private const SurgeryPuppetPart SelectedOnStartPart = SurgeryPuppetPart.Torso;
    private const int ControlsInitAllocateNumber = 8;

    public SurgeryDrapeMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Puppet.Initialize();

        Puppet.SelectedPartChanged += (part, prevPart) =>
        {
            OperationsLabel.Text = Loc.GetString(LocPuppetPartPath(part));
            UpdateOperations(part, prevPart);
        };

        _operations.Clear(); // never knows what coming after all
        foreach (var part in Enum.GetValues<SurgeryPuppetPart>())
        {
            _operations.Add(part, new(ControlsInitAllocateNumber));
        }

        Puppet.SelectedPart = SelectedOnStartPart;
    }

    public void UpdateOperations(SurgeryPuppetPart? currentPart, SurgeryPuppetPart? previousPart)
    {
        if (previousPart != null)
        {
            foreach (var control in _operations[previousPart.Value])
            {
                control.Visible = false;
            }
        }
        if (currentPart != null)
        {
            foreach (var control in _operations[currentPart.Value])
            {
                control.Visible = true;
            }
        }
    }

    public void AddOperations(List<SurgeryStartInfo> graphInfos)
    {
        OperationContainer.RemoveAllChildren();

        foreach (var val in _operations.Values)
        {
            val.Clear();
        }

        foreach (var info in graphInfos)
        {
            var button = MakeOperationButton(info.Surgery, info.CanStart, info.UnavailabilityReason);

            OperationContainer.AddChild(button);
            SetFormattedText(button.RichTextLabel, info.Surgery.Name);

            button.Visible = info.Surgery.TargetPart == Puppet.SelectedPart;

            _operations[info.Surgery.TargetPart].Add(button);
        }
    }

    public void UpdateTarget(EntityUid target)
    {
        Target = target;
        Title = Loc.GetString(HeaderText, ("target", target));
    }

    private SurgeryPerformButton MakeOperationButton(SurgeryGraphPrototype surgeryGraph, bool canStart, string? reason)
    {
        var button = new SurgeryPerformButton(surgeryGraph.ID)
        {
            StyleClasses = { "OpenBoth" },
            Disabled = !canStart
        };

        button.OnPressed += (_) =>
        {
            // So wee do something if button was pressed before pressing by player.
            // Thats why it !Pressed, but meant to be If pressed pressed than
            if (!button.Pressed)
                OnSurgeryConfirmClicked?.Invoke(button.GraphId, Target);
            else
                FooterLeft.Text = Loc.GetString(FooterConfirm);

        };

        if (reason is not null)
        {
            var tooltip = new Tooltip();
            SetFormattedText(tooltip, reason);
            button.TooltipSupplier = (_) => tooltip;
        }
        else
        {
            var formattedText = FormattedMessage.FromMarkupPermissive(Loc.GetString(surgeryGraph.Description));

            if (surgeryGraph.Postscript != null)
            {
                formattedText.PushNewline();
                var postscriptMessage = Loc.GetString(surgeryGraph.Postscript);
                formattedText.AddMessage(FormattedMessage.FromMarkupPermissive(postscriptMessage));
            }

            var tooltip = new Tooltip();
            tooltip.SetMessage(formattedText);
            button.TooltipSupplier = (_) => tooltip;
        }

        return button;
    }

    private string LocPuppetPartPath(SurgeryPuppetPart? part)
    {
        if (part == null)
            return "surgery-puppet-part-none";
        return $"surgery-puppet-part-{Enum.GetName(typeof(SurgeryPuppetPart), part)!.ToLower()}";
    }

    /// <summary>
    /// Some helper function to easily set formatted message from locPath
    /// </summary>
    private void SetFormattedText(Action<FormattedMessage> setterFormatted, Action<string> setterString, string text)
    {
        if (FormattedMessage.TryFromMarkup(text, out var msg))
            setterFormatted(msg);
        else
            setterString(text);
    }

    private void SetFormattedText(RichTextLabel richTextLabel, string locPath)
    {
        SetFormattedText((x) => richTextLabel.SetMessage(x), (x) => richTextLabel.Text = x, Loc.GetString(locPath));
    }

    private void SetFormattedTextFromLocId(Tooltip tooltip, string locPath)
    {
        SetFormattedText(tooltip.SetMessage, (x) => tooltip.Text = x, Loc.GetString(locPath));
    }

    private void SetFormattedText(Tooltip tooltip, string locPath)
    {
        SetFormattedText(tooltip.SetMessage, (x) => tooltip.Text = x, locPath);
    }
}

public readonly record struct SurgeryStartInfo(SurgeryGraphPrototype Surgery, bool CanStart, string? UnavailabilityReason);
