// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Numerics;
using Content.Shared.SS220.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Surgery.SurgeryStartUi;

[GenerateTypedNameReferences]
public sealed partial class SurgeryPuppetBox : Control
{
    /// <summary>
    /// First argument is current part, second is previous
    /// </summary>
    public event Action<SurgeryPuppetPart?, SurgeryPuppetPart?>? SelectedPartChanged;

    public Vector2 Scale
    {
        get => _scale;
        set
        {
            _scale = value;
            ResizeAll();
        }
    }

    private Vector2 _scale = new Vector2(1f);

    public SurgeryPuppetPart? SelectedPart
    {
        get => _selectedPart;
        set
        {
            _selectedPart = HighlightPuppetPart(value);
        }
    }

    private SurgeryPuppetPart? _selectedPart;

    private SortedDictionary<SurgeryPuppetPart, TextureRect> _parts = new();
    private SortedDictionary<SurgeryPuppetPart, TextureRect> _highlightedPart = new();
    private List<PuppetButton> _partButtons = new();

    private const string TexturePath = "/Textures/SS220/Interface/Surgery/puppet";
    private Vector2 _baseTextureSize = new(42f, 42f);

    public SurgeryPuppetBox()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Initialize()
    {
        foreach (var part in Enum.GetValues<SurgeryPuppetPart>())
        {
            var textPart = MakePuppetPartButton(part, _parts, GetPuppetPartTexturePath);

            if (textPart != null)
                this.AddChild(textPart);

            textPart = MakePuppetPartButton(part, _highlightedPart, GetBodyPartelectedTexturePath);

            if (textPart != null)
            {
                this.AddChild(textPart);
                textPart.Visible = false;
            }

            var button = MakePuppetPartButton(part);

            if (button != null)
                AddChild(button);
        }

        ResizeAll();
    }

    private Control? MakePuppetPartButton(SurgeryPuppetPart part, SortedDictionary<SurgeryPuppetPart, TextureRect> bodyPartTexture, Func<SurgeryPuppetPart, string?> pathSpecifier)
    {
        var partTexturePath = pathSpecifier(part);

        if (partTexturePath == null)
            return null;

        var texture = new TextureRect
        {
            Stretch = TextureRect.StretchMode.Keep,
            TexturePath = partTexturePath
        };

        bodyPartTexture.Add(part, texture);

        return texture;
    }

    private Control? MakePuppetPartButton(SurgeryPuppetPart part)
    {
        var offset = GetPartOffset(part);
        var size = GetPartSize(part);

        if (offset == null || size == null)
            return null;

        var thickness = GetPartThickness(offset.Value, size.Value, Scale);

        var button = new PuppetButton
        {
            Part = part,
            SetSize = size.Value * Scale,
            Margin = thickness,
        };

        button.OnPressed += (_) =>
        {
            SelectedPart = part;
        };

        return button;
    }

    private void ResizeAll()
    {
        foreach (var texture in _parts.Values)
        {
            texture.TextureScale = _scale;
        }
        foreach (var texture in _highlightedPart.Values)
        {
            texture.TextureScale = _scale;
        }
        foreach (var button in _partButtons)
        {
            var size = GetPartSize(button.Part);
            var offset = GetPartOffset(button.Part);

            if (size == null || offset == null)
                return;

            button.Margin = GetPartThickness(offset.Value, size.Value, Scale);
            button.SetSize = size.Value * Scale;
        }
        Background.TextureScale = _scale;
    }

    /// <summary>
    /// I hope no one else will need to give a fck what happens here. God bless new med.
    /// </summary>
    private SurgeryPuppetPart? HighlightPuppetPart(SurgeryPuppetPart? puppetPartClicked)
    {
        var newHighlightPart = puppetPartClicked;
        switch (puppetPartClicked)
        {
            case SurgeryPuppetPart.Head:
                switch (_selectedPart)
                {
                    case SurgeryPuppetPart.Head:
                        newHighlightPart = SurgeryPuppetPart.Eyes;
                        break;
                    case SurgeryPuppetPart.Eyes:
                        newHighlightPart = SurgeryPuppetPart.Mouth;
                        break;
                    case SurgeryPuppetPart.Mouth:
                        newHighlightPart = SurgeryPuppetPart.Head;
                        break;
                    default:
                        break;
                }
                break;
            default:
                break;
        }

        if (newHighlightPart == _selectedPart)
            return _selectedPart;

        if (_selectedPart != null)
            RemoveHighlight(_selectedPart.Value);

        if (newHighlightPart != null)
            MakeHighlighted(newHighlightPart.Value);

        SelectedPartChanged?.Invoke(newHighlightPart, _selectedPart);

        return newHighlightPart;
    }

    private void MakeHighlighted(SurgeryPuppetPart part)
    {
        if (_highlightedPart.TryGetValue(part, out var newTextureControl))
            newTextureControl.Visible = true;
        if (_parts.TryGetValue(part, out var oldTextureControl))
            oldTextureControl.Visible = false;
    }

    private void RemoveHighlight(SurgeryPuppetPart part)
    {
        if (_highlightedPart.TryGetValue(part, out var newTextureControl))
            newTextureControl.Visible = false;
        if (_parts.TryGetValue(part, out var oldTextureControl))
            oldTextureControl.Visible = true;
    }


    /// <summary> If you still think why we need new med to make surgery just look into this method. </summary>
    private string? GetPuppetPartTexturePath(SurgeryPuppetPart puppetPart)
    {
        var state = puppetPart switch
        {
            SurgeryPuppetPart.Head => "head.png",
            SurgeryPuppetPart.Torso => "torso.png",
            SurgeryPuppetPart.LeftArm => "left_arm.png",
            SurgeryPuppetPart.RightArm => "right_arm.png",
            SurgeryPuppetPart.LeftHand => "left_hand.png",
            SurgeryPuppetPart.RightHand => "right_hand.png",
            SurgeryPuppetPart.LeftLeg => "left_leg.png",
            SurgeryPuppetPart.RightLeg => "right_leg.png",
            SurgeryPuppetPart.LeftFoot => "left_foot.png",
            SurgeryPuppetPart.RightFoot => "right_foot.png",
            SurgeryPuppetPart.LowerTorso => "butt.png",
            _ => null
        };

        if (state == null)
            return null;
        return $"{TexturePath}/{state}";
    }

    /// <summary> If you still think why we need newMed to make surgery just look into this method too. </summary>
    private string? GetBodyPartelectedTexturePath(SurgeryPuppetPart highlightedPuppetPart)
    {
        var state = highlightedPuppetPart switch
        {
            SurgeryPuppetPart.Head => "head_selected.png",
            SurgeryPuppetPart.Eyes => "eyes_selected.png",
            SurgeryPuppetPart.Mouth => "mouth_selected.png",
            SurgeryPuppetPart.Torso => "torso_selected.png",
            SurgeryPuppetPart.LeftArm => "left_arm_selected.png",
            SurgeryPuppetPart.RightArm => "right_arm_selected.png",
            SurgeryPuppetPart.LeftHand => "left_hand_selected.png",
            SurgeryPuppetPart.RightHand => "right_hand_selected.png",
            SurgeryPuppetPart.LeftLeg => "left_leg_selected.png",
            SurgeryPuppetPart.RightLeg => "right_leg_selected.png",
            SurgeryPuppetPart.LeftFoot => "left_foot_selected.png",
            SurgeryPuppetPart.RightFoot => "right_foot_selected.png",
            SurgeryPuppetPart.LowerTorso => "butt_selected.png",
            _ => null
        };

        if (state == null)
            return null;
        return $"{TexturePath}/{state}";
    }

    private Vector2? GetPartSize(SurgeryPuppetPart part)
    {
        return part switch
        {
            SurgeryPuppetPart.Head => new Vector2(9, 7),
            SurgeryPuppetPart.Torso => new Vector2(9f, 9f),
            SurgeryPuppetPart.RightArm => new Vector2(4f, 6f),
            SurgeryPuppetPart.RightHand => new Vector2(4f, 4f),
            SurgeryPuppetPart.LeftArm => new Vector2(4f, 6f),
            SurgeryPuppetPart.LeftHand => new Vector2(4f, 4f),
            SurgeryPuppetPart.LeftLeg => new Vector2(4f, 7f),
            SurgeryPuppetPart.LeftFoot => new Vector2(6f, 3f),
            SurgeryPuppetPart.RightLeg => new Vector2(4f, 7f),
            SurgeryPuppetPart.RightFoot => new Vector2(6f, 3f),
            SurgeryPuppetPart.LowerTorso => new Vector2(9f, 4f),
            _ => null
        };
    }

    private Vector2? GetPartOffset(SurgeryPuppetPart part)
    {
        return part switch
        {
            SurgeryPuppetPart.Head => new Vector2(16f, 6f),
            SurgeryPuppetPart.Torso => new Vector2(16f, 13f),
            SurgeryPuppetPart.RightArm => new Vector2(12f, 15f),
            SurgeryPuppetPart.RightHand => new Vector2(12f, 21f),
            SurgeryPuppetPart.LeftArm => new Vector2(25f, 15f),
            SurgeryPuppetPart.LeftHand => new Vector2(26f, 21f),
            SurgeryPuppetPart.LeftLeg => new Vector2(21f, 26f),
            SurgeryPuppetPart.LeftFoot => new Vector2(21f, 32f),
            SurgeryPuppetPart.RightLeg => new Vector2(16f, 26f),
            SurgeryPuppetPart.RightFoot => new Vector2(14f, 32f),
            SurgeryPuppetPart.LowerTorso => new Vector2(16f, 22f),
            _ => null
        };
    }

    private Thickness GetPartThickness(Vector2 offset, Vector2 size, Vector2 scale)
    {
        var trueTextureSize = _baseTextureSize * scale;
        Vector2 otherMargin = trueTextureSize - (offset + size) * scale;
        return new Thickness(offset.X * scale.X, offset.Y * scale.Y, otherMargin.X, otherMargin.Y);
    }
    private Thickness GetPartThickness(Vector2 offset, Vector2 size)
    {
        return GetPartThickness(offset, size, Scale);
    }
}

public sealed class PuppetButton : BaseButton
{
    public SurgeryPuppetPart Part;
}


