// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;
using Robust.Shared.Prototypes;
using Content.Shared.SS220.TTS;

namespace Content.Client.SS220.DialogWindowProtoIdUI;

/// <summary>
/// A modified <see cref="DialogWindow"/> window in which you can choose ProtoId for TTS voice
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DialogWindowTTSProtoId : FancyWindow
{
    [Dependency] private IPrototypeManager _prototype = default!;

    private readonly List<(string, LineEdit)> _promptLines;

    private bool _finished;
    private List<string> _ids;

    public Action<Dictionary<string, string>>? OnConfirmed;

    public Action? OnCancelled;

    public DialogWindowTTSProtoId(string title, string desc, List<QuickDialogEntry> entries, Func<object, bool> prototypeSelector, bool ok = true, string? currentVoiceId = null)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Title = title;

        OkButton.Visible = ok;

        _promptLines = new(entries.Count);

        foreach (var entry in entries)
        {
            var box = new BoxContainer();
            box.AddChild(new Label() { Text = entry.Prompt, Align = Label.AlignMode.Center, HorizontalExpand = true});
            Prompts.AddChild(box);

            var boxDesc = new BoxContainer();
            boxDesc.AddChild(new Label() { Text = desc, Align = Label.AlignMode.Center, FontColorOverride = Color.Gray, HorizontalExpand = true });
            Prompts.AddChild(boxDesc);

            var boxEmpty = new BoxContainer();
            boxEmpty.AddChild(new BoxContainer() { MinHeight = 20 });
            Prompts.AddChild(boxEmpty);

            var boxEdit = new BoxContainer();
            var edit = new LineEdit() { HorizontalExpand = true };
            boxEdit.AddChild(edit);

            _promptLines.Add((entry.FieldId, edit));
            Prompts.AddChild(boxEdit);
        }

        // estimated possible voice count
        _ids = new(200);
        foreach (var prototype in _prototype.EnumeratePrototypes<TTSVoicePrototype>())
        {
            if (!prototypeSelector(prototype))
                continue;

            PrototypeIds.AddItem($"{prototype.Name} ({prototype.ID})");
            _ids.Add(prototype.ID);
        }

        PrototypeIds.OnItemSelected += (args) =>
        {
            _promptLines[0].Item2.SetText(_ids[args.Id]);
            PrototypeIds.Select(args.Id);
        };

        OkButton.OnPressed += _ => Confirm();

        OnClose += () =>
        {
            if (!_finished)
                OnCancelled?.Invoke();
        };

        _promptLines[0].Item2.SetText("");
        _promptLines[0].Item2.Editable = false;

        OpenCentered();
    }

    private void Confirm()
    {
        var results = new Dictionary<string, string>();
        foreach (var (field, edit) in _promptLines)
        {
            results[field] = edit.Text;
        }

        _finished = true;
        OnConfirmed?.Invoke(results);
        Close();
    }
}

