// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.Surgery.Graph;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Surgery.BodyAnalyzerUi;

[GenerateTypedNameReferences]
public sealed partial class BodyAnalyzerMenu : FancyWindow
{
    private SurgeryPatientAnalyzer _surgeryPatientAnalyzer = default!;

    public BodyAnalyzerMenu()
    {
        RobustXamlLoader.Load(this);

        _surgeryPatientAnalyzer = IoCManager.Resolve<IEntityManager>().System<SurgeryPatientAnalyzer>();

        OperationList.OnSurgeryClicked += (id, pressed) =>
        {
            OperationDescription.ShowDescription(id, force: true);

            OperationDescription.DataLocked = pressed;
            OperationDescription.Visible = true;
        };

        OperationList.OnSurgeryHovered += (id) =>
        {
            OperationDescription.ShowDescription(id);
            OperationDescription.Visible = true;
        };
    }

    public void ChangeTarget(EntityUid? target)
    {
        if (target is not { } patient)
        {
            TreatmentSuggestion.ShowTargetlessSuggestion();
            PatientStatus.ShowUnknownStatus();
            return;
        }

        var status = _surgeryPatientAnalyzer.GetStatus(patient);
        PatientStatus.ShowStatus(status);
        OperationDescription.UpdateNodeShowTarget(patient);

        TreatmentSuggestion.ShowSuggestion(_surgeryPatientAnalyzer.GetTreatmentRecommendation(status));
    }

    public void UpdatePerformer()
    {
        OperationList.MakeList(false);
        TreatmentSuggestion.ShowTargetlessSuggestion();
        PatientStatus.ShowUnknownStatus();
    }
}
