// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Shared.SS220.Pathology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Pathology;

[GenerateTypedNameReferences]
public sealed partial class DiseaseDiagnoserWindow : DefaultWindow
{
    public DiseaseDiagnoserWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(DiseaseDiagnoserBoundUserInterfaceState state)
    {
        ScanButton.Disabled = !state.HasSample || state.Scanning;
        ScanProgress.Value = state.Progress;

        StatusLabel.Text = !state.HasSample
            ? Loc.GetString("disease-diagnoser-no-sample")
            : state.Scanning
                ? Loc.GetString("disease-diagnoser-scanning")
                : state.HasResult
                    ? Loc.GetString("disease-diagnoser-result")
                    : Loc.GetString("disease-diagnoser-ready");

        VirusNameLabel.Visible = state.VirusName != null;
        if (state.VirusName != null)
            VirusNameLabel.Text = Loc.GetString("disease-diagnoser-virus-name", ("name", state.VirusName));

        SymptomsContainer.RemoveAllChildren();
        foreach (var symptom in state.Symptoms)
            SymptomsContainer.AddChild(new Label { Text = $" · {symptom}" });

        // vectors are only filled in once a strain is fully decoded, so a non-empty set is the cue to show it
        TransmissionLabel.Visible = state.HasResult && state.Transmission != VirusTransmissionVector.None;
        if (TransmissionLabel.Visible)
        {
            var vectors = new List<string>();
            if ((state.Transmission & VirusTransmissionVector.Contact) != 0)
                vectors.Add(Loc.GetString("disease-diagnoser-vector-contact"));
            if ((state.Transmission & VirusTransmissionVector.Proximity) != 0)
                vectors.Add(Loc.GetString("disease-diagnoser-vector-proximity"));

            TransmissionLabel.Text = Loc.GetString("disease-diagnoser-transmission", ("vectors", string.Join(", ", vectors)));
        }

        UnreadableLabel.Visible = state.HasResult && state.UnreadableCount > 0;
        if (UnreadableLabel.Visible)
            UnreadableLabel.Text = Loc.GetString("disease-diagnoser-unreadable", ("count", state.UnreadableCount));

        BufferLabel.Text = Loc.GetString("disease-diagnoser-buffer", ("amount", state.BufferMutagen));
        TransferButton.Disabled = !state.HasSample || state.Scanning;
        CopyButton.Disabled = !state.HasSample || state.Scanning;
    }
}
