// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Shared.SS220.Pathology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.SS220.Pathology;

[GenerateTypedNameReferences]
public sealed partial class DiseaseDiagnoserWindow : DefaultWindow
{
    private readonly IGameTiming _timing;

    private TimeSpan? _operationEnd;
    private TimeSpan _operationDuration;
    private bool _hasResult;
    private bool _scanning;

    public DiseaseDiagnoserWindow()
    {
        RobustXamlLoader.Load(this);
        _timing = IoCManager.Resolve<IGameTiming>();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        ScanProgress.Progress = ComputeProgress();
    }

    private float ComputeProgress()
    {
        // the DNA bar tracks scanning only — printing keeps the helix fully decoded
        if (_scanning && _operationEnd is { } end && _operationDuration > TimeSpan.Zero)
        {
            var remaining = (end - _timing.CurTime) / _operationDuration;
            return Math.Clamp(1f - (float)remaining, 0f, 1f);
        }

        return _hasResult ? 1f : 0f;
    }

    public void UpdateState(DiseaseDiagnoserBoundUserInterfaceState state)
    {
        var busy = state.Scanning || state.Printing;
        ScanButton.Disabled = !state.HasSample || busy;

        _operationEnd = state.OperationEnd;
        _operationDuration = state.OperationDuration;
        _hasResult = state.HasResult;
        _scanning = state.Scanning;
        ScanProgress.Progress = ComputeProgress();

        StationLabel.Text = state.StationName is { } station
            ? Loc.GetString("pathology-console-station", ("name", station))
            : Loc.GetString("pathology-console-station-unknown");

        StatusLabel.Text = !state.HasSample
            ? Loc.GetString("disease-diagnoser-no-sample")
            : state.Scanning
                ? Loc.GetString("disease-diagnoser-scanning")
                : state.Printing
                    ? Loc.GetString("disease-diagnoser-printing")
                    : state.HasResult
                        ? Loc.GetString("disease-diagnoser-result")
                        : Loc.GetString("disease-diagnoser-ready");

        ResultsContainer.DisposeAllChildren();
        foreach (var virus in state.Viruses)
            ResultsContainer.AddChild(BuildVirusBlock(virus));

        BufferLabel.Text = Loc.GetString("disease-diagnoser-buffer", ("amount", state.BufferMutagen));
        TransferButton.Disabled = !state.HasSample || busy;
        CopyButton.Disabled = !state.HasSample || busy;
        PrintButton.Disabled = !state.HasResult || busy;
    }

    private Control BuildVirusBlock(DiseaseDiagnoserVirusResult virus)
    {
        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(0, 0, 0, 6),
        };

        box.AddChild(new Label
        {
            Text = virus.Name != null
                ? Loc.GetString("disease-diagnoser-virus-name", ("name", virus.Name))
                : Loc.GetString("disease-diagnoser-virus-unknown"),
        });

        foreach (var symptom in virus.Symptoms)
            box.AddChild(new Label { Text = $" · {symptom}", Margin = new Thickness(4, 0, 0, 0) });

        // vectors are only filled in once a strain is fully decoded, so a non-empty set is the cue to show it
        if (virus.Transmission != VirusTransmissionVector.None)
        {
            var vectors = new List<string>();
            if ((virus.Transmission & VirusTransmissionVector.Contact) != 0)
                vectors.Add(Loc.GetString("disease-diagnoser-vector-contact"));
            if ((virus.Transmission & VirusTransmissionVector.Proximity) != 0)
                vectors.Add(Loc.GetString("disease-diagnoser-vector-proximity"));

            box.AddChild(new Label
            {
                Text = Loc.GetString("disease-diagnoser-transmission", ("vectors", string.Join(", ", vectors))),
            });
        }

        if (virus.UnreadableCount > 0)
            box.AddChild(new Label
            {
                Text = Loc.GetString("disease-diagnoser-unreadable", ("count", virus.UnreadableCount)),
                StyleClasses = { "LabelSubText" },
            });

        return box;
    }
}
