// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using Content.Shared.SS220.Pathology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Pathology;

[GenerateTypedNameReferences]
public sealed partial class VaccinatorWindow : DefaultWindow
{
    public VaccinatorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(VaccinatorBoundUserInterfaceState state)
    {
        ScanButton.Disabled = !state.HasSample || state.Scanning;
        ScanProgress.Value = state.Progress;

        StatusLabel.Text = !state.HasSample
            ? Loc.GetString("vaccinator-no-sample")
            : state.Scanning
                ? Loc.GetString("vaccinator-scanning")
                : state.HasResult
                    ? Loc.GetString("vaccinator-result")
                    : Loc.GetString("vaccinator-ready");

        VirusNameLabel.Visible = state.VirusName != null;
        if (state.VirusName != null)
            VirusNameLabel.Text = Loc.GetString("vaccinator-virus-name", ("name", state.VirusName));

        SymptomsContainer.RemoveAllChildren();
        foreach (var symptom in state.Symptoms)
            SymptomsContainer.AddChild(new Label { Text = $" · {symptom}" });

        UnreadableLabel.Visible = state.HasResult && state.UnreadableCount > 0;
        if (UnreadableLabel.Visible)
            UnreadableLabel.Text = Loc.GetString("vaccinator-unreadable", ("count", state.UnreadableCount));

        CureLabel.Visible = state.HasResult && (state.CureReagents.Count > 0 || state.CureHidden);
        if (CureLabel.Visible)
        {
            CureLabel.Text = state.CureReagents.Count > 0
                ? Loc.GetString("vaccinator-cure", ("reagents", string.Join(", ", state.CureReagents)))
                : Loc.GetString("vaccinator-cure-hidden");
        }

        BufferLabel.Text = Loc.GetString("vaccinator-buffer", ("amount", state.BufferTricordrazine));
        TransferButton.Disabled = !state.HasSample || state.Scanning;
        CreateVaccineButton.Disabled = !state.HasSample || state.Scanning;
    }
}
