// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Shared.SS220.Pathology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.SS220.Pathology;

[GenerateTypedNameReferences]
public sealed partial class VaccinatorWindow : DefaultWindow
{
    private readonly IGameTiming _timing;

    private TimeSpan? _operationEnd;
    private TimeSpan _operationDuration;
    private bool _hasResult;
    private bool _scanning;

    public VaccinatorWindow()
    {
        RobustXamlLoader.Load(this);
        _timing = IoCManager.Resolve<IGameTiming>();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        ScanProgress.Progress = ComputeProgress();
    }

    private float ComputeProgress()
    {
        if (_scanning && _operationEnd is { } end && _operationDuration > TimeSpan.Zero)
        {
            var remaining = (end - _timing.CurTime) / _operationDuration;
            return Math.Clamp(1f - (float)remaining, 0f, 1f);
        }

        return _hasResult ? 1f : 0f;
    }

    public void UpdateState(VaccinatorBoundUserInterfaceState state)
    {
        var busy = state.Scanning || state.Printing;
        ScanButton.Disabled = !state.HasSample || busy;

        _operationEnd = state.OperationEnd;
        _operationDuration = state.OperationDuration;
        _hasResult = state.HasResult;
        _scanning = state.Scanning;
        ScanProgress.Progress = ComputeProgress();

        StationLabel.Text = state.StationName is { } station
            ? Loc.GetString("pathology-console-station", ("name", station))
            : Loc.GetString("pathology-console-station-unknown");

        StatusLabel.Text = !state.HasSample
            ? Loc.GetString("vaccinator-no-sample")
            : state.Scanning
                ? Loc.GetString("vaccinator-scanning")
                : state.Printing
                    ? Loc.GetString("vaccinator-printing")
                    : state.HasResult
                        ? Loc.GetString("vaccinator-result")
                        : Loc.GetString("vaccinator-ready");

        ResultsContainer.DisposeAllChildren();
        foreach (var virus in state.Viruses)
            ResultsContainer.AddChild(BuildVirusBlock(virus));

        BufferLabel.Text = Loc.GetString("vaccinator-buffer", ("amount", state.BufferTricordrazine));
        TransferButton.Disabled = !state.HasSample || busy;
        CreateVaccineButton.Disabled = !state.HasSample || busy || !state.HasResult;
        PrintButton.Disabled = !state.HasResult || busy;
    }

    private Control BuildVirusBlock(VaccinatorVirusResult virus)
    {
        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(0, 0, 0, 6),
        };

        box.AddChild(new Label
        {
            Text = virus.Name != null
                ? Loc.GetString("vaccinator-virus-name", ("name", virus.Name))
                : Loc.GetString("vaccinator-virus-unknown"),
        });

        if (virus.Suppressed)
            box.AddChild(new Label { Text = Loc.GetString("vaccinator-suppressed") });

        foreach (var symptom in virus.Symptoms)
            box.AddChild(new Label { Text = $" · {symptom}", Margin = new Thickness(4, 0, 0, 0) });

        if (virus.UnreadableCount > 0)
            box.AddChild(new Label
            {
                Text = Loc.GetString("vaccinator-unreadable", ("count", virus.UnreadableCount)),
                StyleClasses = { "LabelSubText" },
            });

        if (virus.CureReagents.Count > 0 || virus.CureHidden)
            box.AddChild(new Label
            {
                Text = virus.CureReagents.Count > 0
                    ? Loc.GetString("vaccinator-cure", ("reagents", string.Join(", ", virus.CureReagents)))
                    : Loc.GetString("vaccinator-cure-hidden"),
            });

        return box;
    }
}
