// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Client.SS220.Surgery.SurgeryStartUi;
using Content.Shared.SS220.Surgery.Graph;
using Content.Shared.SS220.Surgery.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Surgery.UiParts;

[GenerateTypedNameReferences]
public sealed partial class OperationList : Control
{
    public event Action<ProtoId<SurgeryGraphPrototype>, bool>? OnSurgeryClicked;
    public event Action<ProtoId<SurgeryGraphPrototype>>? OnSurgeryHovered;

    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly SharedSurgerySystem _sharedSurgery = default!;

    public OperationList()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sharedSurgery = _entityManager.System<SharedSurgerySystem>();
    }

    public void MakeList(bool ignorePerformerChecks)
    {
        var surgeryGraphsProtos = _prototypeManager.GetInstances<SurgeryGraphPrototype>();
        OperationContainer.RemoveAllChildren();

        var buttonGroup = new ButtonGroup();

        foreach (var (id, proto) in surgeryGraphsProtos)
        {
            if (!ignorePerformerChecks)
            {
                if (_playerManager.LocalEntity == null)
                    return;

                if (!_sharedSurgery.CanStartSurgery(_playerManager.LocalEntity.Value, proto, null, null, out _))
                    continue;
            }

            var button = new SurgeryPerformButton(id)
            {
                StyleClasses = { "OpenBoth" },
                Text = Loc.GetString(proto.Name)
            };

            button.OnMouseEntered += (_) =>
            {
                OnSurgeryHovered?.Invoke(id);
            };

            button.OnPressed += (_) =>
            {
                OnSurgeryClicked?.Invoke(id, button.Pressed);
            };

            button.Group = buttonGroup;

            button.ToolTip = Loc.GetString(proto.Description);

            OperationContainer.AddChild(button);
        }

        OperationContainer.InvalidateArrange();
        OperationContainer.InvalidateMeasure();

        OperationScroll.InvalidateArrange();
        OperationScroll.InvalidateMeasure();

        ContentContainer.InvalidateArrange();
        ContentContainer.InvalidateMeasure();

        InvalidateArrange();
        InvalidateMeasure();
    }

    public void SetAllSurgeryButtonsPress(bool pressed)
    {
        foreach (var child in OperationContainer.Children)
        {
            if (child is not SurgeryPerformButton surgeryButton)
                continue;

            surgeryButton.Pressed = pressed;
        }
    }
}


