// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Client.Message;
using Content.Client.SS220.Surgery.NodeGraphUi;
using Content.Shared.SS220.Surgery.Components;
using Content.Shared.SS220.Surgery.Graph;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.SS220.Surgery.UiParts;

[GenerateTypedNameReferences]
public sealed partial class OperationDescription : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private bool _dataLocked = false;
    public bool DataLocked
    {
        get => _dataLocked;
        set
        {
            _dataLocked = value;
            LockIcon.Visible = value;
        }
    }

    private ProtoId<SurgeryGraphPrototype>? _currentOperation = null;

    public OperationDescription()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateNodeShowTarget(EntityUid patient)
    {
        if (!_entityManager.TryGetComponent<SurgeryPatientComponent>(patient, out var surgeryPatient))
            return;

        var pair = surgeryPatient.OngoingSurgeries.FirstOrNull();
        if (pair is not null)
            ShowDescription(pair.Value.Key, true);

        foreach (var child in OperationContainer.Children)
        {
            if (child is not OperationNodeLabel label)
                continue;

            label.SetActive(pair?.Value == label.NodeId);
        }
    }

    public void ShowDescription(ProtoId<SurgeryGraphPrototype>? id, bool force = false)
    {
        this.Visible = true;
        if (id == _currentOperation)
            return;

        if (!force && DataLocked)
            return;

        _currentOperation = id;
        if (!_currentOperation.HasValue)
            return;

        OperationContainer.RemoveAllChildren();

        if (!_prototypeManager.Resolve(id, out var surgeryProto))
            return;

        AddOperationSteps(surgeryProto);
    }

    private void AddOperationSteps(SurgeryGraphPrototype graph)
    {
        var nodes = graph.Nodes;

        foreach (var node in nodes)
        {
            var nodeLabel = new OperationNodeLabel();
            nodeLabel.SetNodeInfo(node);

            OperationContainer.AddChild(nodeLabel);
        }
    }
}
