// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Surgery.UiParts;

[GenerateTypedNameReferences]
public sealed partial class PatientStatus : Control
{
    [Dependency] private ILocalizationManager _localizationManager = default!;

    public PatientStatus()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void ShowStatus(PatientStatusData data)
    {
        DecayDegree.Visible = true;
        OverallDamage.Visible = true;

        if (data.OverallDamage >= 0)
            OverallDamage.SetMarkup(Loc.GetString("patient-status-overall-damage", ("damage", data.OverallDamage.ToString())));
        else
            OverallDamage.Visible = false;

        MobStatus.SetMarkup(Loc.GetString($"patient-status-mob-state-{data.PatientState.ToString().ToLower()}"));

        if (data.BodyDecayDegree >= 0)
            DecayDegree.SetMarkup(_localizationManager.TryGetString($"patient-status-decay-degree-{data.BodyDecayDegree}", out var locStr)
                                ? locStr : data.BodyDecayDegree.ToString());
        else
            DecayDegree.Visible = false;

        if (data.BrainRotDegree > 0)
            BrainRotStatus.SetMarkup(Loc.GetString($"patient-status-brain-rot-degree", ("degree", data.BrainRotDegree)));
        else
            BrainRotStatus.SetMarkup(Loc.GetString($"patient-status-brain-rot-none"));
    }

    public void ShowUnknownStatus()
    {
        OverallDamage.SetMarkup(Loc.GetString("patient-status-overall-damage", ("damage", "-")));
        MobStatus.SetMarkup(Loc.GetString("patient-status-mob-state-invalid"));
        DecayDegree.SetMarkup(Loc.GetString("patient-status-decay-degree--1"));
        BrainRotStatus.SetMarkup(Loc.GetString($"patient-status-brain-rot-invalid"));
    }
}
