// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Text;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Surgery.UiParts;

[GenerateTypedNameReferences]
public sealed partial class TreatmentSuggestion : Control
{
    public string InSectionTextPrefix = "  - ";

    private static readonly LocId EmptyTargetless = "treatment-recommendation-target-less";
    private static readonly LocId EmptyTreatmentPlaceholder = "treatment-recommendation-empty";

    private static readonly LocId ProblemSectionName = "treatment-recommendation-problem-section-name";
    private static readonly LocId OperationSectionName = "treatment-recommendation-operation-section-name";
    private static readonly LocId SuggestionSectionName = "treatment-recommendation-suggestion-section-name";

    public TreatmentSuggestion()
    {
        RobustXamlLoader.Load(this);
    }

    public void ShowTargetlessSuggestion()
    {
        TreatmentSuggestionText.Text = Loc.GetString(EmptyTargetless);
    }

    public void ShowSuggestion(TreatmentRecommendation recommendation)
    {
        StringBuilder builder = new();

        AddSection(recommendation.Problems, Loc.GetString(ProblemSectionName), builder);
        AddSection(recommendation.Operations, Loc.GetString(OperationSectionName), builder);
        AddSection(recommendation.Suggestions, Loc.GetString(SuggestionSectionName), builder);

        if (builder.Length > 0)
            TreatmentSuggestionText.Text = builder.ToString();
        else
            TreatmentSuggestionText.Text = Loc.GetString(EmptyTreatmentPlaceholder);

    }

    private void AddSection(List<string> dataText, string sectionName, StringBuilder builder)
    {
        if (dataText.Count == 0)
            return;

        builder.AppendLine(sectionName);

        foreach (var text in dataText)
        {
            builder.Append(InSectionTextPrefix);
            builder.AppendLine(text);
        }
    }
}
